# example usage:
# 
# PATH_TO_YOUR_REPO=/data/repos/atlassian
# sudo ln -s ${PATH_TO_YOUR_REPO} /atlassian
#
# build nginx image, and bring up all containers (-d means in the background)
# cd /atlassian && docker build -t nginx_with_config . && docker-compose up -d
#
# docker stats # to monitor memory usage (confluence may take up to 2GB, give your docker host at least 4GB total)
# docker logs



# create nginx image with `cd /atlassian && docker build -t nginx_with_config .`
nginx:
  image: nginx_with_config
  restart: always
  ports:
    - "80:80"
    - "443:443"
  links:
    - stash
    - jira
    - confluence
    - crowd
    - bamboo
  # volumes:
  #   - nginx.conf:/etc/nginx/nginx.conf

stash:
  image: mhubig/atlassian-stash
  restart: always
  links:
    - database
  volumes:
    - /atlassian/atlassian-stash/home:/opt/stash-home

jira:
  image: mhubig/atlassian-jira
  restart: always
  links:
    - database
  volumes:
    - /atlassian/atlassian-jira/home:/opt/jira-home

confluence:
  image: mhubig/atlassian-confluence
  restart: always
  links:
    - database
  volumes:
    - /atlassian/atlassian-confluence/home:/opt/confluence-home

crowd:
  image: mhubig/atlassian-crowd
  restart: always
  links:
    - database
  volumes:
    - /atlassian/atlassian-crowd/home:/opt/crowd-home

bamboo:
  image: mhubig/atlassian-bamboo
  restart: always
  links:
    - database
  volumes:
    - /atlassian/atlassian-bamboo/home:/opt/bamboo-home

database:
  image: postgres:9.4
  restart: always
  volumes:
    - data:/var/lib/postgresql/data
    - /atlassian/atlassian-confluence/setup-confluence-db.sh:/docker-entrypoint-initdb.d/setup-confluence-db.sh
    - /atlassian/atlassian-crowd/setup-crowd-db.sh:/docker-entrypoint-initdb.d/setup-crowd-db.sh
    - /atlassian/atlassian-jira/setup-jira-db.sh:/docker-entrypoint-initdb.d/setup-jira-db.sh
    - /atlassian/atlassian-stash/setup-stash-db.sh:/docker-entrypoint-initdb.d/setup-stash-db.sh
    - /atlassian/atlassian-bamboo/setup-bamboo-db.sh:/docker-entrypoint-initdb.d/setup-bamboo-db.sh
    - tmp:/tmp/dumps # import backups
